Update language for narrow type test.
w3c/vc-data-model-2.0-test-suite pull request #46
Opened 2023-12-11 21:47 UTC by aljones15

Changes the narrow type test to a SHOULD

2023-12-12 15:07 UTC, BigBlueHat requested changes

2023-12-12 15:07 UTC, BigBlueHat commented on tests/10-vcdm2.js
>          ' can process this additional information.', async function() {
```suggestion
        '(like ExampleDegreeCredential, for example) so software systems ' +
        ' can more easily detect and process this additional information.', async function() {
```

May as well match the current text exactly. Helps keep things connected.

2023-12-12 15:20 UTC, BigBlueHat requested changes

2023-12-12 18:55 UTC, aljones15 commented on tests/10-vcdm2.js
> +        ' can more easily detect and process this additional information.', async function() {
yeah length issues pop up a lot with the github comments will work on it in a moment.

2023-12-12 18:57 UTC, aljones15 commented on tests/10-vcdm2.js
> +        ' can more easily detect and process this additional information.', async function() {
address here: https://github.com/w3c/vc-data-model-2.0-test-suite/pull/46/commits/3f9700833da3a3f49f60a556fa9a83aa4035b006

2023-12-13 15:04 UTC, BigBlueHat approved these changes

2023-12-13 15:23 UTC, merged