Add issuer name tests.
w3c/vc-data-model-2.0-test-suite pull request #47
Opened 2023-12-12 14:13 UTC by aljones15

2023-12-12 15:05 UTC, BigBlueHat requested changes
@aljones15 good start. I think key to these specific tests will be negative versions. The "value object" for example, MUST NOT have any additional properties. So the following would be an invalid value for `name`:
```json
{
      "@value":"ExampleIssuer",
      "@language": "en",
      "url": "http://example.com/issuer" 
    }
```

And arrays of value objects are also valid--to support multiple languages.

We should also get an `@direction` example tested in their also.

2023-12-14 14:34 UTC, BigBlueHat approved these changes
Excellent. Thank you!

2023-12-14 15:01 UTC, JSAssassin approved these changes

2023-12-14 15:31 UTC, aljones15 commented on tests/10-vcdm2.js
> +      ' Base Direction.', async function() {
I'll take this, but it probably breaks the linter.

2023-12-14 15:32 UTC, JSAssassin commented
Also need to add a changelog entry for the test like in the other PR.

2023-12-15 17:59 UTC, merged