Expand issuer property tests.
w3c/vc-data-model-2.0-test-suite pull request #50
Opened 2023-12-12 18:54 UTC by aljones15

2023-12-13 15:02 UTC, BigBlueHat requested changes
This one's tricky. URLs are wonderfully varied and composable things, so I don't think most/any issuer would actually choke on the negative example here. A Verifier might...but only if/when it tried to dereference it.

2023-12-13 16:58 UTC, aljones15 commented on tests/input/credential-issuer-object-id-not-url-fail.json
> +    "id": "https ://not-a-url/issuer/foo"
I could replace this with a number or null, a number seems best. This has been tested on 2 implementations and this does actually cause all url parsers used by implementers to fail. However, I think a different type such as a number might get the issue across better?

2023-12-13 16:59 UTC, aljones15 commented on tests/input/credential-issuer-object-id-not-url-fail.json
> +  "validFrom": "2023-02-26T00:37:06Z",
not sure how that snuck in, I'll make a check for `validFrom` in the test data to ensure it's only on tests for that property.

2023-12-13 20:10 UTC, aljones15 commented on tests/input/credential-issuer-object-id-not-url-fail.json
> +  "validFrom": "2023-02-26T00:37:06Z",
I removed `validFrom` from all the VCs in this specific test: https://github.com/w3c/vc-data-model-2.0-test-suite/pull/50/commits/ecfa55febf5002f70d3d3069b042f640394c6274

https://github.com/w3c/vc-data-model-2.0-test-suite/pull/50/commits/3ce010952e0eeda6a0ef1d795c2d7c1cb55bd1bb

2023-12-21 19:04 UTC, dlongley commented
Can we put a number or boolean in the field (non-string) instead? If we already have such a test, let's strike this, if not, let's just use a non-string to handle the test case here.

2024-01-02 14:09 UTC, aljones15 commented
> Can we put a number or boolean in the field (non-string) instead? If we already have such a test, let's strike this, if not, let's just use a non-string to handle the test case here.

we can change to a number or boolean @BigBlueHat thoughts here? I actually think this is a fine solution.

2024-01-02 14:22 UTC, BigBlueHat commented
> we can change to a number or boolean @BigBlueHat thoughts here? I actually think this is a fine solution.

Fine by me.

2024-01-03 21:29 UTC, JSAssassin approved these changes
LGTM! Needs a changelog entry.

2024-01-04 14:44 UTC, BigBlueHat approved these changes

2024-01-04 16:28 UTC, merged